# Generated by Django 5.0.6 on 2024-06-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0002_note_owner_note_tags_alter_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
